
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/tabletennis
    username: postgres
    password: mike
    driverClassName: org.postgresql.Driver
server:
  port: 8085